use mavenmovies;
-- Basic Aggregate Fuction
-- Q1. Retrieve the total number of rentals made in the sakila database??
select count(rental_id) from rental;
-- Q2. Find the average rental duration in days of movies rented from the sakila database??
select avg(rental_duration) from film;
-- Sting Function
-- Q3. Display the first_name and last_name of customers in uppercase??
select upper(first_name) as FIRST_NAME , upper(last_name) as LAST_NAME from customer;
-- Q4. Extract the month from the rental_date and display alongside the rental_id??
select rental_id , month(rental_date) from rental;
-- Group by
-- Q5. Retrieve the count of rentals for each customer(Display customerID and count of rentals)??
select customer_id , count(rental_id) from rental group by customer_id;
-- Q6. Find the total revenue generated by each store??
select amount , sum(amount) from payment group by amount;
-- Joins
-- Q7. Display the title of movie , customers first name and last name who rented it??
select film.title , first_name , last_name from film 
inner join inventory on film.film_id=inventory.film_id 
inner join rental on inventory.inventory_id=rental.inventory_id 
inner join customer on rental.customer_id=customer.customer_id;
-- Q8. Retrieve the names of all actors who have appeared in the film "Gone with the Wind"??
select first_name , last_name from film inner join film_actor on film.film_id=film_actor.film_id 
inner join actor on film_actor.actor_id=actor.actor_id where title="gone trouble";
-- Group By
-- Q1. Determine the total number of rentals for each category of movies??
select rental_id , category_id , count(rental_id) from rental inner join film on rental.rental_id=film.film_id  
inner join film_category on film.film_id=film_category.category_id group by rental_id;
-- Q2. Find the average rental rate of movies in each language??
select rental_rate , avg(rental_rate) from film inner join language on 
film.language_id=language.language_id group by rental_rate;
-- Joins
-- Q3. Retrieve the customer names along with the total amount they have spent on rentals??
select first_name , last_name , amount , sum(amount) from payment 
inner join customer on payment.customer_id=customer.customer_id 
inner join rental on customer.customer_id=rental.customer_id group by first_name , last_name , amount;
-- Q4. List the titles of movies rented by each customer in a particular city(for eg: London)??
select title , first_name , last_name , city, count(city) from film 
inner join inventory on film.film_id=inventory.film_id
inner join rental on inventory.inventory_id=rental.inventory_id 
inner join customer on rental.customer_id=customer.customer_id
inner join address on customer.address_id=address.address_id
inner join city on address.city_id=city.city_id where city="london" 
group by title , first_name , last_name , city;
-- Advanced Join and Group By 
-- Q5. Display the top 5 rented movies along with the number of times they have been rented??
select title , rental_duration , count(rental_duration) from film inner join inventory on 
film.film_id=inventory.inventory_id inner join rental on inventory.inventory_id=rental.rental_id 
group by title , rental_duration limit 5;







